-- firebird5
CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol VARCHAR(50) NOT NULL
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido1 VARCHAR(100) NOT NULL,
    apellido2 VARCHAR(100),
    telefono VARCHAR(20),
    email VARCHAR(100) UNIQUE NOT NULL,
    usuario VARCHAR(50) UNIQUE NOT NULL,
    pass VARCHAR(255) NOT NULL,
    ruta_imagen VARCHAR(255),
    rol_id INTEGER,
    nombre_completo COMPUTED BY (nombre || ' ' || apellido1 || ' ' || apellido2),
    CONSTRAINT fk_rol FOREIGN KEY (rol_id) REFERENCES roles(id_rol)
);